[package]
name = "lp-bot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serenity = { version = "0.10", default-features = false, features = ["client", "gateway", "rustls_backend", "model", "unstable_discord_api", "cache"] }
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
serde_json = "1.0"
chrono = "0.4"
timezone-abbreviations = "0.1.0"
rspotify = "0.11"
rusqlite = "0.27"
regex = "1.6"
anyhow = "1.0"
