[package]
name = "lp-bot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serenity = { version = "0.11", default-features = false, features = ["client", "gateway", "rustls_backend", "model", "unstable_discord_api", "cache"] }
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
chrono = "0.4"
timezone-abbreviations = "0.1.0"
rusqlite = "0.28"
regex = "1.6"
anyhow = "1.0"
fallible-iterator = "0.2"
serenity-command-derive = { version = "0.1.0", path = "../bots/serenity-command-derive" }
serenity-command = { version = "0.1.0", path = "../bots/serenity-command" }
serenity-command-handler = { version = "0.1.0", path = "../bots/serenity-command-handler" }
image = "0.24.3"
